version: '3.8'

name: MTVectorKnowledgeBase
services:
  app:
    container_name: mtpy
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vectordb
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    volumes:
      - ./:/app
      - /Users:/host/Users
    depends_on:
      - db
    restart: always

  db:
    container_name: mtpg
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
    #or load from the .env file: e.g. POSTGRES_USER=${POSTGRES_USER}
    #POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectordb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: